var PRODUCTS = {
    skateboards: [
        {
            type: "skateboards",
            boardBrand: "Anti-Hero",
            boardSize: 9.1,
            wheelSize: 63,
            wheelColor: "Red",
            price: 72.00,
            image: "images/Anti1.jpeg",
        },
        {
            type: "skateboards",
            boardBrand: "Anti-Hero",
            boardSize: 8.5,
            wheelSize: 59,
            wheelColor: "Green",
            price: 63.00,
            image: "images/Anti2.jpeg",
        },
        {
            type: "skateboards",
            boardBrand: "Darkroom",
            boardSize: 8.125,
            wheelSize: 52,
            wheelColor: "Black",
            price: 59.00,
            image: "images/Darkroom1.jpeg",
        },
        {
            type: "skateboards",
            boardBrand: "Flip",
            boardSize: 8.75,
            wheelSize: 62,
            wheelColor: "Orange",
            price: 70.00,
            image: "images/Flip1.jpeg",
        },
        {
            type: "skateboards",
            boardBrand: "Flip",
            boardSize: 9.25,
            wheelSize: 46,
            wheelColor: "Purple",
            price: 64.00,
            image: "images/Flip2.jpeg",
        },
        {
            type: "skateboards",
            boardBrand: "Pizza",
            boardSize: 8.25,
            wheelSize: 58,
            wheelColor: "Blue",
            price: 67.00,
            image: "images/Pizza1.jpeg",
        },
        {
            type: "skateboards",
            boardBrand: "Reals",
            boardSize: 9.5,
            wheelSize: 56,
            wheelColor: "Blue",
            price: 69.00,
            image: "images/Anti1.jpeg",
        }
    ],
}